---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                   Define global settings
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  vars_files:
     - ../../../global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        desired_state:    present
        #desired_state:   absent
        #desired_status:  modified,created
        #desired_status:  deleted

    - name:               apic details
      set_fact:
        apic_info:        &apic_info
          host:           "{{ apic_info.host }}"
          username:       "{{ apic_info.username }}"
          password:       "{{ apic_info.password }}"
          validate_certs: no

        rest_info:        &rest_info
          use_proxy:      no
          path:           /api/mo/.json
          method:         post
  tags:                   always

#==============================================================================================
# Begin Plays
#
# Available Tags:
#               snapshot
#               vrfs
#==============================================================================================
- import_playbook:        ../../../snapshot.yaml
  vars:
    snapshotDescription:  Prior-to-configuring-Common-Tenant-VRFs
  tags:                   snapshot

#==============================================================================================
# Create VRFs
#==============================================================================================
- name:                            Configure VRF
  hosts:                           localhost
  connection:                      local
  gather_facts:                    no

  vars_files:
     - ./vars/vrf-vars.yaml

  tasks:
    - name:                        Create/Delete VRF
      aci_vrf:
        <<:                        *apic_info
        tenant:                    "{{ item.tenant }}"
        vrf:                       "{{ item.vrf }}"
        description:               "{{ item.descr }}"
        policy_control_preference: enforced
        state:                     "{{ desired_state }}"
      with_items:
        - "{{ vrf }}"
      loop_control:
        pause: 1
  tags:
    - vrf
